-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (..)


type Mutation
    = Mutation


type Post
    = Post


type Post_mutation_response
    = Post_mutation_response


type Post_tag
    = Post_tag


type Post_tag_aggregate
    = Post_tag_aggregate


type Post_tag_aggregate_fields
    = Post_tag_aggregate_fields


type Post_tag_max_fields
    = Post_tag_max_fields


type Post_tag_min_fields
    = Post_tag_min_fields


type Post_tag_mutation_response
    = Post_tag_mutation_response


type Query
    = Query


type Tag
    = Tag


type Tag_mutation_response
    = Tag_mutation_response
