-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (..)


type Mutation
    = Mutation


type Post
    = Post


type Post_aggregate
    = Post_aggregate


type Post_aggregate_fields
    = Post_aggregate_fields


type Post_max_fields
    = Post_max_fields


type Post_min_fields
    = Post_min_fields


type Post_mutation_response
    = Post_mutation_response


type Post_tag
    = Post_tag


type Post_tag_aggregate
    = Post_tag_aggregate


type Post_tag_aggregate_fields
    = Post_tag_aggregate_fields


type Post_tag_max_fields
    = Post_tag_max_fields


type Post_tag_min_fields
    = Post_tag_min_fields


type Post_tag_mutation_response
    = Post_tag_mutation_response


type Purchase
    = Purchase


type Purchase_aggregate
    = Purchase_aggregate


type Purchase_aggregate_fields
    = Purchase_aggregate_fields


type Purchase_max_fields
    = Purchase_max_fields


type Purchase_min_fields
    = Purchase_min_fields


type Purchase_mutation_response
    = Purchase_mutation_response


type Query
    = Query


type Tag
    = Tag


type Tag_aggregate
    = Tag_aggregate


type Tag_aggregate_fields
    = Tag_aggregate_fields


type Tag_max_fields
    = Tag_max_fields


type Tag_min_fields
    = Tag_min_fields


type Tag_mutation_response
    = Tag_mutation_response


type User
    = User


type User_aggregate
    = User_aggregate


type User_aggregate_fields
    = User_aggregate_fields


type User_max_fields
    = User_max_fields


type User_min_fields
    = User_min_fields


type User_mutation_response
    = User_mutation_response
