-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.ScalarCodecs exposing (..)

import Api.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias Date =
    Api.Scalar.Date


type alias Id =
    Api.Scalar.Id


type alias Jwt =
    Api.Scalar.Jwt


type alias Timestamptz =
    Api.Scalar.Timestamptz


type alias Uuid =
    Api.Scalar.Uuid


codecs : Api.Scalar.Codecs Date Id Jwt Timestamptz Uuid
codecs =
    Api.Scalar.defineCodecs
        { codecDate = defaultCodecs.codecDate
        , codecId = defaultCodecs.codecId
        , codecJwt = defaultCodecs.codecJwt
        , codecTimestamptz = defaultCodecs.codecTimestamptz
        , codecUuid = defaultCodecs.codecUuid
        }
