-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Post_min_fields exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import CustomScalars
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


body : SelectionSet (Maybe String) Api.Object.Post_min_fields
body =
    Object.selectionForField "(Maybe String)" "body" [] (Decode.string |> Decode.nullable)


date : SelectionSet (Maybe CustomScalars.Date) Api.Object.Post_min_fields
date =
    Object.selectionForField "(Maybe CustomScalars.Date)" "date" [] (CustomScalars.codecs |> Api.Scalar.unwrapCodecs |> .codecDate |> .decoder |> Decode.nullable)


id : SelectionSet (Maybe CustomScalars.Uuid) Api.Object.Post_min_fields
id =
    Object.selectionForField "(Maybe CustomScalars.Uuid)" "id" [] (CustomScalars.codecs |> Api.Scalar.unwrapCodecs |> .codecUuid |> .decoder |> Decode.nullable)


iv : SelectionSet (Maybe String) Api.Object.Post_min_fields
iv =
    Object.selectionForField "(Maybe String)" "iv" [] (Decode.string |> Decode.nullable)


user_id : SelectionSet (Maybe CustomScalars.Uuid) Api.Object.Post_min_fields
user_id =
    Object.selectionForField "(Maybe CustomScalars.Uuid)" "user_id" [] (CustomScalars.codecs |> Api.Scalar.unwrapCodecs |> .codecUuid |> .decoder |> Decode.nullable)
