-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Purchase_max_fields exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import CustomScalars
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


checkout_session_id : SelectionSet (Maybe String) Api.Object.Purchase_max_fields
checkout_session_id =
    Object.selectionForField "(Maybe String)" "checkout_session_id" [] (Decode.string |> Decode.nullable)


created_at : SelectionSet (Maybe CustomScalars.Timestamptz) Api.Object.Purchase_max_fields
created_at =
    Object.selectionForField "(Maybe CustomScalars.Timestamptz)" "created_at" [] (CustomScalars.codecs |> Api.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder |> Decode.nullable)


email : SelectionSet (Maybe String) Api.Object.Purchase_max_fields
email =
    Object.selectionForField "(Maybe String)" "email" [] (Decode.string |> Decode.nullable)


id : SelectionSet (Maybe CustomScalars.Uuid) Api.Object.Purchase_max_fields
id =
    Object.selectionForField "(Maybe CustomScalars.Uuid)" "id" [] (CustomScalars.codecs |> Api.Scalar.unwrapCodecs |> .codecUuid |> .decoder |> Decode.nullable)


updated_at : SelectionSet (Maybe CustomScalars.Timestamptz) Api.Object.Purchase_max_fields
updated_at =
    Object.selectionForField "(Maybe CustomScalars.Timestamptz)" "updated_at" [] (CustomScalars.codecs |> Api.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder |> Decode.nullable)
