-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.User_min_fields exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import CustomScalars
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


created_at : SelectionSet (Maybe CustomScalars.Timestamptz) Api.Object.User_min_fields
created_at =
    Object.selectionForField "(Maybe CustomScalars.Timestamptz)" "created_at" [] (CustomScalars.codecs |> Api.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder |> Decode.nullable)


id : SelectionSet (Maybe CustomScalars.Uuid) Api.Object.User_min_fields
id =
    Object.selectionForField "(Maybe CustomScalars.Uuid)" "id" [] (CustomScalars.codecs |> Api.Scalar.unwrapCodecs |> .codecUuid |> .decoder |> Decode.nullable)


nonce : SelectionSet (Maybe String) Api.Object.User_min_fields
nonce =
    Object.selectionForField "(Maybe String)" "nonce" [] (Decode.string |> Decode.nullable)


password : SelectionSet (Maybe String) Api.Object.User_min_fields
password =
    Object.selectionForField "(Maybe String)" "password" [] (Decode.string |> Decode.nullable)


purchase_id : SelectionSet (Maybe CustomScalars.Uuid) Api.Object.User_min_fields
purchase_id =
    Object.selectionForField "(Maybe CustomScalars.Uuid)" "purchase_id" [] (CustomScalars.codecs |> Api.Scalar.unwrapCodecs |> .codecUuid |> .decoder |> Decode.nullable)


token : SelectionSet (Maybe String) Api.Object.User_min_fields
token =
    Object.selectionForField "(Maybe String)" "token" [] (Decode.string |> Decode.nullable)


updated_at : SelectionSet (Maybe CustomScalars.Timestamptz) Api.Object.User_min_fields
updated_at =
    Object.selectionForField "(Maybe CustomScalars.Timestamptz)" "updated_at" [] (CustomScalars.codecs |> Api.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder |> Decode.nullable)
