-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Enum.Post_select_column exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| select columns of table "post"

  - Body - column name
  - Date - column name
  - Id - column name
  - User\_id - column name

-}
type Post_select_column
    = Body
    | Date
    | Id
    | User_id


list : List Post_select_column
list =
    [ Body, Date, Id, User_id ]


decoder : Decoder Post_select_column
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "body" ->
                        Decode.succeed Body

                    "date" ->
                        Decode.succeed Date

                    "id" ->
                        Decode.succeed Id

                    "user_id" ->
                        Decode.succeed User_id

                    _ ->
                        Decode.fail ("Invalid Post_select_column type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : Post_select_column -> String
toString enum =
    case enum of
        Body ->
            "body"

        Date ->
            "date"

        Id ->
            "id"

        User_id ->
            "user_id"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Post_select_column
fromString enumString =
    case enumString of
        "body" ->
            Just Body

        "date" ->
            Just Date

        "id" ->
            Just Id

        "user_id" ->
            Just User_id

        _ ->
            Nothing
