-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Enum.Tag_select_column exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| select columns of table "tag"

  - Created\_at - column name
  - Id - column name
  - Iv - column name
  - Name - column name
  - Updated\_at - column name
  - User\_id - column name

-}
type Tag_select_column
    = Created_at
    | Id
    | Iv
    | Name
    | Updated_at
    | User_id


list : List Tag_select_column
list =
    [ Created_at, Id, Iv, Name, Updated_at, User_id ]


decoder : Decoder Tag_select_column
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "created_at" ->
                        Decode.succeed Created_at

                    "id" ->
                        Decode.succeed Id

                    "iv" ->
                        Decode.succeed Iv

                    "name" ->
                        Decode.succeed Name

                    "updated_at" ->
                        Decode.succeed Updated_at

                    "user_id" ->
                        Decode.succeed User_id

                    _ ->
                        Decode.fail ("Invalid Tag_select_column type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : Tag_select_column -> String
toString enum =
    case enum of
        Created_at ->
            "created_at"

        Id ->
            "id"

        Iv ->
            "iv"

        Name ->
            "name"

        Updated_at ->
            "updated_at"

        User_id ->
            "user_id"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Tag_select_column
fromString enumString =
    case enumString of
        "created_at" ->
            Just Created_at

        "id" ->
            Just Id

        "iv" ->
            Just Iv

        "name" ->
            Just Name

        "updated_at" ->
            Just Updated_at

        "user_id" ->
            Just User_id

        _ ->
            Nothing
