-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Enum.Tag_constraint exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| unique or primary key constraints on table "tag"

  - Tag\_pkey - unique or primary key constraint

-}
type Tag_constraint
    = Tag_pkey


list : List Tag_constraint
list =
    [ Tag_pkey ]


decoder : Decoder Tag_constraint
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "tag_pkey" ->
                        Decode.succeed Tag_pkey

                    _ ->
                        Decode.fail ("Invalid Tag_constraint type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : Tag_constraint -> String
toString enum =
    case enum of
        Tag_pkey ->
            "tag_pkey"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Tag_constraint
fromString enumString =
    case enumString of
        "tag_pkey" ->
            Just Tag_pkey

        _ ->
            Nothing
