-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Enum.Tag_select_column exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| select columns of table "tag"

  - Ciphertext - column name
  - Created\_at - column name
  - Id - column name
  - Iv - column name

-}
type Tag_select_column
    = Ciphertext
    | Created_at
    | Id
    | Iv


list : List Tag_select_column
list =
    [ Ciphertext, Created_at, Id, Iv ]


decoder : Decoder Tag_select_column
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "ciphertext" ->
                        Decode.succeed Ciphertext

                    "created_at" ->
                        Decode.succeed Created_at

                    "id" ->
                        Decode.succeed Id

                    "iv" ->
                        Decode.succeed Iv

                    _ ->
                        Decode.fail ("Invalid Tag_select_column type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : Tag_select_column -> String
toString enum =
    case enum of
        Ciphertext ->
            "ciphertext"

        Created_at ->
            "created_at"

        Id ->
            "id"

        Iv ->
            "iv"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Tag_select_column
fromString enumString =
    case enumString of
        "ciphertext" ->
            Just Ciphertext

        "created_at" ->
            Just Created_at

        "id" ->
            Just Id

        "iv" ->
            Just Iv

        _ ->
            Nothing
