-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Enum.User_select_column exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| select columns of table "user"

  - Created\_at - column name
  - Id - column name
  - Nonce - column name
  - Password - column name
  - Purchase\_id - column name
  - Token - column name
  - Updated\_at - column name

-}
type User_select_column
    = Created_at
    | Id
    | Nonce
    | Password
    | Purchase_id
    | Token
    | Updated_at


list : List User_select_column
list =
    [ Created_at, Id, Nonce, Password, Purchase_id, Token, Updated_at ]


decoder : Decoder User_select_column
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "created_at" ->
                        Decode.succeed Created_at

                    "id" ->
                        Decode.succeed Id

                    "nonce" ->
                        Decode.succeed Nonce

                    "password" ->
                        Decode.succeed Password

                    "purchase_id" ->
                        Decode.succeed Purchase_id

                    "token" ->
                        Decode.succeed Token

                    "updated_at" ->
                        Decode.succeed Updated_at

                    _ ->
                        Decode.fail ("Invalid User_select_column type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : User_select_column -> String
toString enum =
    case enum of
        Created_at ->
            "created_at"

        Id ->
            "id"

        Nonce ->
            "nonce"

        Password ->
            "password"

        Purchase_id ->
            "purchase_id"

        Token ->
            "token"

        Updated_at ->
            "updated_at"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe User_select_column
fromString enumString =
    case enumString of
        "created_at" ->
            Just Created_at

        "id" ->
            Just Id

        "nonce" ->
            Just Nonce

        "password" ->
            Just Password

        "purchase_id" ->
            Just Purchase_id

        "token" ->
            Just Token

        "updated_at" ->
            Just Updated_at

        _ ->
            Nothing
